---
title: 'Summary Paper: Crime in DC'
author: "Rebecca Felix, GWU Intro to Data Science DATS 6101"
# date: "today"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

__Introduction - Sophia__


__Theoretical Framework and Data Source- Sophia__


__Data Description - Jiaxi__
	__Types of variables and summary__
	
	
__Summary Statistics  - Rebecca__

It is clear that total crime incidences were lower in 2020 than in 2021 for every type of crime besides arson and burglary. The beginning of the COVID-19 pandemic restrictions took place during this time, and we suspect that this is a factor as to why crime rates are lower in 2020. Activities and events were cancelled and people were isolating at home which may have caused less crime activity. Overall, total crime increased by 2,840 incidents.


__By ward and year- Rebecca__
Then, in order to examine the data in each of the different locations and compare them to one another, we aggregated the crime statistics by ward, type of offense, and year. 

(insert code here?)

Across each type of crime, Ward 3 had the lowest amount of incidences. Ward 2 has the highest total amount of crime with Ward 2 following. 



	__By time of day - Jiaxi__
	
	__Correlation coefficient - Jiaxi__
	
	__Hypothesis testing - Sophia__
	
__What does it all mean/Discussion - everybody writes small summaries of their parts and we compile it together__


__Biases and Directions for Future Research - Rebecca__

